services:
  lime_simul_demo_yuu:
    # WhisperでNVIDIA CUDAを使えるようにする
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
