FROM osrf/ros:humble-desktop-full

SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    xterm \
    python3-pip \
    python3-colcon-common-extensions \
    ros-humble-rclpy \
    ros-humble-sensor-msgs \
    ros-humble-std-msgs \
    ros-humble-geometry-msgs \
    ros-humble-cv-bridge \
    ros-humble-rmw-cyclonedds-cpp \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --no-cache-dir --upgrade pip setuptools wheel

RUN python3 -m pip install --no-cache-dir --ignore-installed \
    numpy==1.26.4 \
    matplotlib==3.8.4 \
    opencv-python-headless==4.10.0.84 \
    ultralytics \
    roboflow \
    inference-sdk

WORKDIR /root/yolo_ws
RUN mkdir -p src /root/bin

RUN echo "source /opt/ros/humble/setup.bash" >> /root/.bashrc && \
    echo "if [ -f /root/yolo_ws/install/setup.bash ]; then source /root/yolo_ws/install/setup.bash; fi" >> /root/.bashrc && \
    echo "export ROS_DOMAIN_ID=20" >> /root/.bashrc && \
    echo "export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp" >> /root/.bashrc && \
    echo 'export PATH=$PATH:/root/bin' >> /root/.bashrc

WORKDIR /root/yolo_ws

CMD ["bash"]